### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hemanth** [fp-js/meta#1]
- [x] template repo for modules
- [x] auto-currying
  - [x] curry1, curry2, curry3 (should be enough for a start)
- [x] compose
- [x] flip (flips the arguments of a function)
- [x] always
- [x] ifElse
- [x] cond
- [x] and
- [x] or
- [ ] where
- [ ] typeof
- [ ] typeis
- [ ] select
- [x] map
- [x] reduce 
- [x] some
- [x] flatten
- [x] filter
- [x] find
- [x] pluck
- [x] mayBe
- [ ] either 
- [ ] none
- [ ] noop
- [x] apply
- [ ] call

**Comment by m59peacemaker** [comment]
It appears no new modules have been added in quite some time. I use Ramda often, but I prefer a totally modular approach, which you have taken with `fp-js`. I need to get a functional `merge-with` on npm soon. I'd love to contribute it and many other modules to `fp-js` as opportunity allows. Is `fp-js` open to that kind of growth?

**Comment by hemanth** [comment]
Oh yeah, indeed! PRs are most welcomed.
